---
deployment:
  tasks:
    - export REPOPATH=/home/ozerichs/repositories/OzerichinoSchool/*
    - export SITEPATH=/home/ozerichs/app/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
